"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import {
  ArrowRight,
  Brain,
  Check,
  ChevronRight,
  Clipboard,
  GitBranch,
  Menu,
  Network,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/components/auth/auth-provider";

const yaml = `# .powerful.yml
rules:
  - Never log raw tokens or authorization headers
  - Use parameterized queries for all database access
  - Require pagination on public list endpoints
  - Wrap payment webhooks in idempotent transactions`;

const pipeline = ["fetch_pr", "fetch_config", "chunk_changes", "search_memory", "score_risk", "llm_review", "post_comments", "notify_complete"];

function FadeIn({ children, delay = 0, className = "" }: { children: React.ReactNode; delay?: number; className?: string }) {
  return <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: 0.6, delay }} className={className}>{children}</motion.div>;
}

function Logo() {
  return <Link href="/" className="flex items-center gap-3" aria-label="Powerful home"><span className="grid size-9 place-items-center rounded-xl bg-[#7C3AED] text-white shadow-lg shadow-violet-200"><Sparkles className="size-4" /></span><span className="text-lg font-extrabold tracking-tight text-[#1A1A2E]">Powerful</span><Badge className="hidden rounded-full border-0 bg-[#EDE9FE] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-[#7C3AED] sm:inline-flex">Agent</Badge></Link>;
}

function ReviewCard() {
  return <motion.div animate={{ y: [0, -8, 0] }} transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }} className="relative mx-auto max-w-xl rounded-2xl border border-[#E5E7EB] bg-white p-5 text-left shadow-2xl shadow-violet-200/70 sm:p-7">
    <div className="absolute -inset-4 -z-10 rounded-[2rem] bg-violet-200/40 blur-2xl" />
    <div className="flex items-start justify-between gap-4 border-b border-[#E5E7EB] pb-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#1A1A2E] text-white"><GitBranch className="size-4" /></span><div><p className="text-[11px] font-semibold uppercase tracking-wider text-[#9CA3AF]">Pull request #284</p><p className="font-mono text-sm font-bold text-[#1A1A2E]">feat: add user authentication middleware</p></div></div><Badge className="shrink-0 rounded-full border-0 bg-red-50 px-2.5 py-1 text-[10px] font-bold text-red-600">RISK: 84/100</Badge></div>
    <div className="mt-5 rounded-xl border border-red-100 bg-red-50/60 p-4"><div className="mb-3 flex items-center gap-2 text-xs font-bold text-[#1A1A2E]"><span className="grid size-6 place-items-center rounded-md bg-[#7C3AED] text-white"><Sparkles className="size-3" /></span>Powerful Agent <span className="font-normal text-[#9CA3AF]">· just now</span></div><p className="text-sm leading-6 text-[#374151]">Raw authorization token logged to stdout on line 100. Use <code className="rounded bg-white px-1.5 py-0.5 font-mono text-xs text-[#7C3AED]">hashToken()</code> instead.</p><p className="mt-3 text-xs font-semibold text-[#7C3AED]">99% confidence · learned from 12 approved rules</p></div>
    <div className="mt-5 flex items-center justify-between gap-3"><span className="text-xs text-[#9CA3AF]">Suggested change found in memory</span><div className="flex gap-2"><Button variant="ghost" size="sm" className="text-xs">Dismiss</Button><Button size="sm" className="gap-1.5 rounded-lg bg-[#7C3AED] text-xs hover:bg-[#5B21B6]">Approve &amp; save rule <Check className="size-3.5" /></Button></div></div>
  </motion.div>;
}

function MemoryMockup() { return <div className="rounded-2xl border border-[#E5E7EB] bg-white p-5 shadow-xl"><div className="flex items-center justify-between border-b border-[#F0F0F0] pb-4"><div className="flex items-center gap-2"><Brain className="size-4 text-[#7C3AED]" /><span className="text-sm font-bold text-[#1A1A2E]">Team memory bank</span></div><Badge variant="muted" className="font-mono text-[10px]">v2.0 pgvector</Badge></div><div className="flex flex-col gap-3 py-4">{["Never log raw authorization tokens", "Use typed error boundaries in API routes", "Prefer cursor pagination over offset"] .map((rule, i) => <div key={rule} className="flex items-start gap-3 rounded-xl bg-[#F8F7FC] p-3"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-600"><Check className="size-3" /></span><div><p className="text-xs font-semibold text-[#374151]">{rule}</p><p className="mt-1 font-mono text-[10px] text-[#9CA3AF]">approved_rule_{String(i + 1).padStart(2, "0")} · 98% match</p></div></div>)}</div><div className="border-t border-[#F0F0F0] pt-4 text-xs font-semibold text-[#7C3AED]">Shared with your whole team →</div></div>; }

function PipelineMockup() { return <div className="overflow-hidden rounded-2xl border border-violet-200 bg-white p-5 shadow-xl"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold text-[#1A1A2E]"><Network className="size-4 text-[#7C3AED]" />Review pipeline</div><span className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-emerald-600"><span className="size-1.5 rounded-full bg-emerald-500" /> live</span></div><div className="flex min-w-[620px] items-center gap-1">{pipeline.map((node, i) => <div key={node} className="flex items-center gap-1"><div className={`rounded-lg border px-2 py-2 text-center font-mono text-[9px] font-semibold ${i === 4 ? "border-[#7C3AED] bg-[#7C3AED] text-white shadow-lg shadow-violet-200" : "border-[#E5E7EB] bg-[#FAFAFA] text-[#6B7280]"}`}>{node}</div>{i < pipeline.length - 1 && <ArrowRight className="size-3 shrink-0 text-[#C4B5FD]" />}</div>)}</div><p className="mt-5 font-mono text-[10px] text-[#9CA3AF]">8 stages completed in 1.14s</p></div>; }

function RiskMockup() { return <div className="rounded-2xl border border-[#E5E7EB] bg-white p-6 text-center shadow-xl"><div className="mx-auto grid size-44 place-items-center rounded-full" style={{ background: "conic-gradient(#ef4444 0deg 302deg, #FEE2E2 302deg 360deg)" }}><div className="grid size-32 place-items-center rounded-full bg-white"><div><p className="text-3xl font-black tracking-tight text-[#1A1A2E]">84</p><p className="text-[10px] font-bold uppercase tracking-wider text-red-500">out of 100</p></div></div></div><div className="mt-6 grid grid-cols-2 gap-2">{["Diff 30pt", "Files 20pt", "Critical 35pt", "Dismiss 15pt"].map((item) => <span key={item} className="rounded-lg bg-red-50 px-3 py-2 text-[11px] font-bold text-red-600">{item}</span>)}</div></div>; }

export default function Home() {
  const { user } = useAuth();
  const [copied, setCopied] = useState(false);
  return <main className="min-h-screen overflow-visible bg-[#F5F3EF] text-[#1A1A2E]">
    <header className="sticky top-0 z-50 border-b border-[#E5E7EB] bg-white"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-8 text-sm font-medium text-[#374151] lg:flex"><a href="#features" className="hover:text-[#7C3AED]">Features</a><a href="#architecture" className="hover:text-[#7C3AED]">Architecture</a><a href="#risk" className="hover:text-[#7C3AED]">Risk Engine</a><a href="#pricing" className="hover:text-[#7C3AED]">Pricing</a></nav><div className="flex items-center gap-3"><Link href={user ? "/dashboard" : "/install"} className="hidden text-sm font-semibold text-[#374151] sm:block">{user ? "Dashboard" : "Log in"}</Link><Link href="/install"><Button className="rounded-full bg-[#7C3AED] px-5 hover:bg-[#5B21B6]">Connect GitHub <ArrowRight data-icon="inline-end" /></Button></Link><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open menu"><Menu /></Button></div></div></header>
    <section className="px-5 pb-24 pt-20 sm:pt-28"><div className="mx-auto max-w-4xl text-center"><p className="mb-6 text-xs font-bold uppercase tracking-[0.18em] text-[#7C3AED]">Autonomous PR Review · Vector Memory Bank</p><h1 className="text-5xl font-black leading-[0.98] tracking-[-0.05em] sm:text-7xl lg:text-8xl">Code reviews that learn<br className="hidden sm:block" /> from your team.</h1><p className="mx-auto mt-7 max-w-xl text-lg leading-8 text-[#6B7280]">Powerful remembers every approved suggestion and gets smarter with every PR — no repeated nitpicks, ever.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/install"><Button size="lg" className="rounded-full bg-[#7C3AED] px-8 hover:bg-[#5B21B6]">Connect GitHub <ArrowRight data-icon="inline-end" /></Button></Link><a href="#features"><Button size="lg" variant="outline" className="rounded-full border-[#1A1A2E] px-8 text-[#1A1A2E]">See it in action</Button></a></div><p className="mt-5 text-xs font-medium text-[#9CA3AF]">No credit card required · Free for 50 PRs/month</p><div className="mt-16"><ReviewCard /></div></div></section>
    <section className="border-y border-[#E5E7EB] bg-white"><div className="mx-auto flex max-w-6xl flex-wrap justify-center divide-x divide-[#E5E7EB] py-5 text-center">{["1.14s avg review speed", "98.4% memory recall accuracy", "8-stage LangGraph pipeline", "Groq Llama 3.3 70B"].map((item) => <div key={item} className="px-5 py-2 text-xs font-bold text-[#1A1A2E] sm:px-7 sm:text-sm">{item}</div>)}</div></section>
    <section id="features" className="bg-white"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><FadeIn className="grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><div><Badge className="mb-6 rounded-full border-0 bg-[#EDE9FE] text-[#7C3AED]">Vector Memory</Badge><h2 className="text-4xl font-black leading-tight tracking-[-0.04em] sm:text-5xl">Stops repeating itself. Learns your team.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-[#6B7280]">Every approved suggestion is stored as a vector embedding. Future PRs touching similar code get smarter reviews automatically.</p><a href="#architecture" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#7C3AED]">Learn more <ArrowRight className="size-4" /></a></div><MemoryMockup /></FadeIn></div></section>
    <section id="architecture" className="bg-gradient-to-br from-[#EDE9FE] to-[#F5F3FF]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><FadeIn className="grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><div className="order-2 lg:order-1"><PipelineMockup /></div><div className="order-1 lg:order-2"><Badge className="mb-6 rounded-full border-0 bg-white text-[#7C3AED]">LangGraph Pipeline</Badge><h2 className="text-4xl font-black leading-tight tracking-[-0.04em] sm:text-5xl">8 stages. Sub-second latency.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-[#6B7280]">From webhook to inline GitHub comment in under 1.5 seconds. Every PR passes through a deterministic state machine.</p><a href="#how-it-works" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#7C3AED]">Learn more <ArrowRight className="size-4" /></a></div></FadeIn></div></section>
    <section id="risk" className="bg-white"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><FadeIn className="grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><div><Badge className="mb-6 rounded-full border-0 bg-red-50 text-red-600">PR Risk Scoring</Badge><h2 className="text-4xl font-black leading-tight tracking-[-0.04em] sm:text-5xl">Know which PRs need human eyes.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-[#6B7280]">Every PR gets a 0-100 risk score based on diff size, file criticality, and historical dismissal rates. Posted instantly as a GitHub commit status.</p><a href="#how-it-works" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#7C3AED]">Learn more <ArrowRight className="size-4" /></a></div><RiskMockup /></FadeIn></div></section>
    <section className="bg-gradient-to-br from-[#ECFEFF] to-[#F0F9FF]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><FadeIn className="grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><div className="order-2 lg:order-1"><div className="rounded-2xl bg-[#1A1A2E] p-5 font-mono text-xs leading-6 text-slate-300 shadow-2xl"><div className="mb-4 flex items-center justify-between border-b border-white/10 pb-3 text-[10px] text-slate-500"><span>.powerful.yml</span><button onClick={() => { navigator.clipboard.writeText(yaml); setCopied(true); setTimeout(() => setCopied(false), 1600); }} className="flex items-center gap-1 text-slate-400 hover:text-white" aria-label="Copy configuration"><Clipboard className="size-3" />{copied ? "Copied" : "Copy"}</button></div><pre className="whitespace-pre-wrap"><span className="text-violet-300">{yaml}</span></pre></div></div><div className="order-1 lg:order-2"><Badge className="mb-6 rounded-full border-0 bg-white text-[#0891B2]">Custom Rules</Badge><h2 className="text-4xl font-black leading-tight tracking-[-0.04em] sm:text-5xl">Your standards. Enforced automatically.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-[#6B7280]">Drop a .powerful.yml file into any repo. The agent reads your rules on every PR and enforces them alongside learned memory.</p><a href="#how-it-works" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#7C3AED]">Learn more <ArrowRight className="size-4" /></a></div></FadeIn></div></section>
    <section id="how-it-works"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><FadeIn><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#7C3AED]">Simple by design</p><h2 className="mt-4 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Up and running in 3 steps.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[{n:"01", t:"Install", d:"Install the GitHub App. Powerful discovers your repos automatically."},{n:"02", t:"Configure", d:"Add a .powerful.yml to set custom rules. Or skip it — defaults work great."},{n:"03", t:"Merge smarter", d:"Every PR gets reviewed, scored, and commented in under 1.5 seconds."}].map((step) => <div key={step.n} className="rounded-2xl border border-[#E5E7EB] bg-white p-7 shadow-sm"><span className="font-mono text-sm font-bold text-[#7C3AED]">{step.n}</span><h3 className="mt-8 text-xl font-extrabold">{step.t}</h3><p className="mt-3 leading-7 text-[#6B7280]">{step.d}</p></div>)}</div></FadeIn></div></section>
    <section id="pricing" className="bg-[#4C1D95] px-5 py-24 text-white"><FadeIn className="mx-auto max-w-3xl text-center"><h2 className="text-4xl font-black tracking-[-0.04em] sm:text-6xl">Start reviewing smarter today.</h2><p className="mt-5 text-lg text-violet-200">Free for 50 PRs/month. No credit card required.</p><Link href="/install"><Button size="lg" className="mt-9 rounded-full bg-white px-8 text-[#5B21B6] hover:bg-violet-50">Connect GitHub <ArrowRight data-icon="inline-end" /></Button></Link></FadeIn></section>
    <footer className="bg-[#1A1A2E] px-5 py-14 text-white lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-12 md:flex-row"><div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#7C3AED]"><Sparkles className="size-4" /></span><span className="text-lg font-extrabold">Powerful</span></div><p className="mt-4 text-sm text-slate-400">Autonomous PR Review SaaS</p></div><div className="grid grid-cols-2 gap-12 text-sm sm:grid-cols-3"><div><p className="mb-4 font-bold">Product</p><div className="flex flex-col gap-3 text-slate-400"><a href="#features">Dashboard</a><a href="/install">GitHub App</a><a href="#architecture">Architecture</a><a href="#risk">Simulator</a></div></div><div><p className="mb-4 font-bold">Company</p><div className="flex flex-col gap-3 text-slate-400"><a href="#">About</a><a href="#">GitHub</a><a href="#pricing">Pricing</a></div></div></div></div><div className="mt-14 border-t border-white/10 pt-6 text-xs text-slate-500">© 2026 Powerful. Production-Grade AI Engineering.</div></div></footer>
  </main>;
}
